'''The tool interface is defined in the BaseTool class which is a subclass of the Runnable Interface.

The key attributes that correspond to the tool's schema:

name: The name of the tool.
description: A description of what the tool does.
args: Property that returns the JSON schema for the tool's arguments.
The key methods to execute the function associated with the tool:

invoke: Invokes the tool with the given arguments.
ainvoke: Invokes the tool with the given arguments, asynchronously. Used for async programming with Langchain.
'''

# How to pass run time values to tools
# We can use the InjectedToolArg annotation to mark certain parameters of our Tool, 
# like user_id as being injected at runtime, meaning they shouldn't be generated by the model

import os
import dotenv
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage

# Load environment variables
dotenv.load_dotenv()

# Constants
OPENAI_MODEL = "gpt-4o-mini"
MODEL_PROVIDER = "openai"
SYSTEM_MESSAGE = ""
TOOLS = []

# Define structured output format using Pydantic
class ResponseFormatter1(BaseModel):
    """Always use this tool to structure your response to the user."""
    question: str = Field(description="The user's individal question present in prompt")
    logic: str = Field(description="The logic used to answer the prompt")
    tool_calls: str = Field(description="List of tool calls done by model to answer the prompt")
    answer: str = Field(description="The answer to the user's question")
    followup_question: str = Field(description="A followup question the user could ask")

# Define a tool for multiplication
@tool
def multiply_two_num(a: int, b: int) -> int:
    """Use when you need to multiply two numbers."""
    return a * b

@tool
def add_two_num(a: int, b: int) -> int:
    """Use when you need to add two numbers."""
    return a + b

@tool
def subtract_two_num(a: int, b: int) -> int:
    """Use when you need to subtract two numbers."""
    return a - b

# Add tools to the list
TOOLS.append(multiply_two_num)
TOOLS.append(add_two_num)
TOOLS.append(subtract_two_num)

# Initialize chat model
def init_model_with_tools(tools):
    model = init_chat_model(model=OPENAI_MODEL, model_provider=MODEL_PROVIDER)
    model_with_tools = model.bind_tools(tools)
    return model_with_tools

model = init_model_with_tools(TOOLS)

# Wrap model with structured output schema
structured_llm = model.with_structured_output(ResponseFormatter1)

# Custom system message to enforce the output structure
def system_message():
    return """
You are a teacher and must solve problems using the available tools.

Always structure your response using this format:
- question: The exact question(s) the user asked.
- logic: Step-by-step reasoning used to solve it.
- tool_calls: Mention any tool names used (e.g., multiply_two_num, add_two_num) and inputs.
- answer: The final numeric result(s).
- followup_question: A natural follow-up related to the question.
"""

SYSTEM_MESSAGE = system_message()

# Define message examples
messages1 = [
    SystemMessage(content=SYSTEM_MESSAGE),
    HumanMessage(content="What is the powerhouse of the cell?"),
]

messages2 = [
    SystemMessage(content=SYSTEM_MESSAGE),
    HumanMessage(content="Multiply 2 by 3?"),
]

messages3 = [
    SystemMessage(content=SYSTEM_MESSAGE),
    HumanMessage(content='''
                 Solve below maths problem: 
                 Q1: 2 + 3 = ?,
                 Q2: 4 * 5 = ?,
                 Q3: 6 - 7 = ?,
                 Q4: 8 / 9 = ?
                 '''),
]

# Invoke messages and capture both structured and raw responses
def run_prompt(messages, label=""):
    print(f"\n--- {label} ---")

    # Get structured output
    structured_response = structured_llm.invoke(messages)

    # Print structured content
    print("Question:", structured_response.question)
    print("Logic:", structured_response.logic)
    print("Tool Calls:", structured_response.tool_calls)
    print("Answer:", structured_response.answer)
    print("Followup Question:", structured_response.followup_question)
    print()

# Run both prompts
run_prompt(messages1, label="Test 1: Biology Question")
run_prompt(messages2, label="Test 2: Math Tool Question")
run_prompt(messages3, label="Test 3: Multiple Math Tool Question")
